#!/usr/bin/env bash
# One-command launcher for the trivia stack.
#
#   ./run.sh           # dev mode  — uvicorn --reload + next dev (LAN-only)
#   ./run.sh --prod    # prod-ish  — uvicorn + next build && next start (LAN-only)
#   ./run.sh --tunnel  # ngrok     — dev servers + 2 ngrok tunnels (any network)
#
# First run auto-installs Python venv, pip deps, npm deps, and seeds env files.
# Ctrl-C cleanly shuts down everything.

set -euo pipefail

cd "$(dirname "$0")"

MODE="dev"
case "${1:-}" in
  --prod)   MODE="prod" ;;
  --tunnel) MODE="tunnel" ;;
  "")       MODE="dev" ;;
  *)        echo "Usage: $0 [--prod|--tunnel]" >&2; exit 1 ;;
esac

C_RESET=$'\033[0m'; C_DIM=$'\033[2m'; C_BLUE=$'\033[34m'; C_PURPLE=$'\033[35m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'

log()  { printf "%s[run]%s %s\n" "$C_BLUE" "$C_RESET" "$*"; }
warn() { printf "%s[run]%s %s\n" "$C_YELLOW" "$C_RESET" "$*"; }
err()  { printf "%s[run]%s %s\n" "$C_RED" "$C_RESET" "$*" >&2; }

# --- Backend setup ---
if [[ ! -d .venv ]]; then
  log "creating Python venv (.venv)…"
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate

NEED_PIP=0
if ! python -c "import fastapi" 2>/dev/null; then NEED_PIP=1; fi
if [[ -f backend/requirements.txt && ( ! -f .venv/.req-stamp || backend/requirements.txt -nt .venv/.req-stamp ) ]]; then
  NEED_PIP=1
fi
if [[ $NEED_PIP -eq 1 ]]; then
  log "installing Python deps…"
  pip install --quiet --upgrade pip
  pip install --quiet -r backend/requirements.txt
  touch .venv/.req-stamp
fi

if [[ ! -f backend/.env && -f backend/.env.example ]]; then
  warn "backend/.env missing — copying from .env.example (set OPENAI_API_KEY for call-a-friend)"
  cp backend/.env.example backend/.env
fi

# --- Frontend setup ---
if [[ ! -d frontend/node_modules ]]; then
  log "installing npm deps (first run, may take ~1 min)…"
  (cd frontend && npm install --no-fund --no-audit --silent)
fi
if [[ ! -f frontend/.env.local ]]; then
  log "seeding frontend/.env.local"
  cp frontend/.env.local.example frontend/.env.local
fi

# --- Tunnel mode: ngrok bring-up ---
NGROK_PID=""
if [[ $MODE == "tunnel" ]]; then
  if ! command -v ngrok >/dev/null 2>&1; then
    err "ngrok not installed. Install: brew install ngrok  (or https://ngrok.com/download)"
    exit 1
  fi
  if [[ ! -f ngrok.yml.example ]]; then
    err "ngrok.yml.example missing — repo broken."
    exit 1
  fi

  # Load NGROK_* + FRONTEND_URL placeholder from backend/.env without exporting OPENAI_API_KEY noise.
  set -a
  # shellcheck disable=SC1091
  source backend/.env
  set +a

  : "${NGROK_AUTHTOKEN:?NGROK_AUTHTOKEN unset — add to backend/.env (see ngrok.yml.example)}"
  : "${NGROK_BACKEND_DOMAIN:?NGROK_BACKEND_DOMAIN unset — add to backend/.env (reserve a free static domain at https://dashboard.ngrok.com/domains)}"

  log "rendering .ngrok.yml from template…"
  # envsubst only replaces the two vars we declare — avoids accidental ${...} stomping.
  envsubst '${NGROK_AUTHTOKEN} ${NGROK_BACKEND_DOMAIN}' < ngrok.yml.example > .ngrok.yml

  log "starting ngrok (backend → ${C_PURPLE}https://${NGROK_BACKEND_DOMAIN}${C_RESET}, frontend → random)…"
  ngrok start --all --config .ngrok.yml --log .ngrok.log --log-format json >/dev/null 2>&1 &
  NGROK_PID=$!

  # Poll the ngrok local API until both tunnels appear.
  log "waiting for ngrok to allocate tunnels…"
  TUNNEL_JSON=""
  for _ in $(seq 1 30); do
    if TUNNEL_JSON=$(curl -fsS http://127.0.0.1:4040/api/tunnels 2>/dev/null); then
      if python3 -c "import json,sys;d=json.loads(sys.stdin.read());sys.exit(0 if len(d.get('tunnels',[]))>=2 else 1)" <<<"$TUNNEL_JSON"; then
        break
      fi
    fi
    sleep 0.5
  done

  BACKEND_URL=$(printf '%s' "$TUNNEL_JSON" | python3 -c "import json,sys
for t in json.load(sys.stdin).get('tunnels',[]):
    if t.get('name')=='backend':
        print(t['public_url']); break")
  FRONTEND_URL_TUN=$(printf '%s' "$TUNNEL_JSON" | python3 -c "import json,sys
for t in json.load(sys.stdin).get('tunnels',[]):
    if t.get('name')=='frontend':
        print(t['public_url']); break")

  if [[ -z "$BACKEND_URL" || -z "$FRONTEND_URL_TUN" ]]; then
    err "could not read tunnel URLs from ngrok API. Check .ngrok.log."
    kill "$NGROK_PID" 2>/dev/null || true
    exit 1
  fi

  log "writing frontend/.env.local  ← NEXT_PUBLIC_API_URL=$BACKEND_URL"
  cat > frontend/.env.local <<EOF
# Auto-generated by ./run.sh --tunnel — overwritten on each run.
NEXT_PUBLIC_API_URL=$BACKEND_URL
NEXT_PUBLIC_TUNNEL_URL=$FRONTEND_URL_TUN
EOF

  # Backend reads FRONTEND_URL via load_dotenv (override=False). Exporting wins.
  # Include localhost so opening the frontend at http://localhost:3000 still
  # connects (CORS is comma-separated; backend trims trailing slashes).
  export FRONTEND_URL="$FRONTEND_URL_TUN,http://localhost:3000,http://127.0.0.1:3000"
fi

# --- Boot ---
PIDS=()
cleanup() {
  log "shutting down…"
  if [[ -n "$NGROK_PID" ]]; then
    kill "$NGROK_PID" 2>/dev/null || true
  fi
  for pid in "${PIDS[@]:-}"; do
    kill "$pid" 2>/dev/null || true
  done
  wait 2>/dev/null || true
  exit 0
}
trap cleanup INT TERM

log "starting backend  → ${C_PURPLE}http://localhost:8000${C_RESET}  ${C_DIM}(uvicorn)${C_RESET}"
if [[ $MODE == "prod" ]]; then
  uvicorn backend.main:app --host 0.0.0.0 --port 8000 &
else
  uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload &
fi
PIDS+=($!)

log "starting frontend → ${C_PURPLE}http://localhost:3000${C_RESET}  ${C_DIM}(next)${C_RESET}"
if [[ $MODE == "prod" ]]; then
  (cd frontend && npm run build && npm run start) &
else
  (cd frontend && npm run dev) &
fi
PIDS+=($!)

if [[ $MODE == "tunnel" ]]; then
  BAR="══════════════════════════════════════════════════════════════════"
  printf "\n%s%s%s\n" "$C_GREEN" "$BAR" "$C_RESET"
  printf " %sPLAY HERE (laptop):%s  %s%s%s\n" "$C_GREEN" "$C_RESET" "$C_PURPLE" "$FRONTEND_URL_TUN" "$C_RESET"
  printf "   %s↳ vs Computer:%s     %s%s/cpu%s\n" "$C_DIM" "$C_RESET" "$C_PURPLE" "$FRONTEND_URL_TUN" "$C_RESET"
  printf "   %s↳ vs Friends:%s      %s%s/host%s\n" "$C_DIM" "$C_RESET" "$C_PURPLE" "$FRONTEND_URL_TUN" "$C_RESET"
  printf " %sFriends scan the QR shown on /host (cellular data works).%s\n" "$C_DIM" "$C_RESET"
  printf " %sbackend API:%s          %s%s%s\n" "$C_DIM" "$C_RESET" "$C_PURPLE" "$BACKEND_URL" "$C_RESET"
  printf " %sngrok inspector:%s      %shttp://127.0.0.1:4040%s\n" "$C_DIM" "$C_RESET" "$C_PURPLE" "$C_RESET"
  printf "%s%s%s\n\n" "$C_GREEN" "$BAR" "$C_RESET"

  # Auto-open frontend tunnel URL so the host never accidentally lands on
  # localhost (which would make the QR encode an unreachable address).
  # Wait a few seconds for next dev to start compiling so the first request
  # doesn't race a 503.
  (
    sleep 4
    if command -v open >/dev/null 2>&1; then
      open "$FRONTEND_URL_TUN/host" >/dev/null 2>&1 || true
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$FRONTEND_URL_TUN/host" >/dev/null 2>&1 || true
    fi
  ) &
fi

log "${C_GREEN}both servers up. Ctrl-C to stop.${C_RESET}"
wait
